package main

var VINE_TOMATO string = "#EF5026"
var EGGPLANT string = "#3C3755"
var RED_PEPPER string = "#C52728"
var PURPLE_CABBAGE string = "#8E4980"
var BROCCOLI string = "#2C401B"
var BRUSSELS_SPROUTS string = "#86A23E"
var POTATO string = "#D79851"
var RHUBARB string = "#C15866"
var APPLE string = "#E5493D"
var OKRA string = "#5E7434"
var JICAMA string = "#CB726E"
var FENNEL string = "#CBC7A1"
var LEMON string = "#FAF599"
var APRICOT string = "#FFBE30"
var AVOCADO string = "#C9C561"
var BLUEBERRY string = "#353535"
var SOUR_CHERRY string = "#AF1317"
var BEET string = "#D73C2A"
var ASPERAGUS string = "#C6BD62"
var WATERCRESS string = "#9FB43B"
var TANGERINE string = "#FAA21D"
var BANANA string = "#FDDF6F"
var SPRING_ONION string = "#702C23"
var PEAR string = "#C8C846"
var CHARD string = "#547838"
var FIG string = "#68281F"
var GOLDEN_KIWI string = "#F6D063"
var YELLOW_BELLPEPPER string = "#FDC647"
var SQUASH_BLOSSOM string = "#ECCC55"
var RED_KIDNEY_BEAN string = "#CB9274"
var SQUASH string = "#FBE70E"
var MUSCAT_GRAPES string = "#AD709A"
var RED_BELLPEPPER string = "#D12728"
var CARROT string = "#E75F25"
var GREEN_CABBAGE string = "#B4C346"
var PINEAPPLE string = "#E2A528"
var DRAGON_FRUIT string = "#C9A62E"
var ZUCCHINI string = "#93A13F"
var KALE string = "#47642E"
var CUCUMBER string = "#456033"
var PEACH string = "#F47747"
var FIDDLEHEAD string = "#597A41"
var PURPLE_CAULIFLOWER string = "#753C67"
var CARAMBOLA string = "#E1B828"
var PAPAYA string = "#EFAE20"
var LONG_BEAN string = "#8A9E6D"
var STRAWBERRY string = "#D62D28"
var TURNIP string = "#B64885"
var RADISH string = "#B32225"
var ARTICHOKE string = "#879C3D"
var BUTTER_SQUASH string = "#ECB481"
var MANGOSTEEN string = "#9A1C1F"

var NMSCOLORS = []string{
	VINE_TOMATO,
	EGGPLANT,
	RED_PEPPER,
	PURPLE_CABBAGE,
	BROCCOLI,
	BRUSSELS_SPROUTS,
	POTATO,
	RHUBARB,
	APPLE,
	OKRA,
	JICAMA,
	FENNEL,
	LEMON,
	APRICOT,
	AVOCADO,
	BLUEBERRY,
	SOUR_CHERRY,
	BEET,
	ASPERAGUS,
	WATERCRESS,
	TANGERINE,
	BANANA,
	SPRING_ONION,
	PEAR,
	CHARD,
	FIG,
	GOLDEN_KIWI,
	YELLOW_BELLPEPPER,
	SQUASH_BLOSSOM,
	RED_KIDNEY_BEAN,
	SQUASH,
	MUSCAT_GRAPES,
	RED_BELLPEPPER,
	CARROT,
	GREEN_CABBAGE,
	PINEAPPLE,
	DRAGON_FRUIT,
	ZUCCHINI,
	KALE,
	CUCUMBER,
	PEACH,
	FIDDLEHEAD,
	PURPLE_CAULIFLOWER,
	CARAMBOLA,
	PAPAYA,
	LONG_BEAN,
	STRAWBERRY,
	TURNIP,
	RADISH,
	ARTICHOKE,
	BUTTER_SQUASH,
	MANGOSTEEN}
